//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankiety_PZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ankiety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ankiety()
        {
            this.Pytania = new HashSet<Pytania>();
            this.Wyniki = new HashSet<Wyniki>();
        }
    
        public int IdAnkiety { get; set; }
        public int IdUzytkownika { get; set; }
        public string NazwaAnkiety { get; set; }
        public bool Aktywna { get; set; }
    
        public virtual Uzytkownicy Uzytkownicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pytania> Pytania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wyniki> Wyniki { get; set; }
    }
}
