//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ankiety_PZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ankiety> Ankiety { get; set; }
        public virtual DbSet<Pytania> Pytania { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
        public virtual DbSet<Wyniki> Wyniki { get; set; }
        public virtual DbSet<Wynik> Wynik { get; set; }
        public virtual DbSet<WyswietlAnkiety> WyswietlAnkiety { get; set; }
    
        public virtual ObjectResult<WypelnijAnkiete_Result> WypelnijAnkiete(Nullable<int> idankiety)
        {
            var idankietyParameter = idankiety.HasValue ?
                new ObjectParameter("idankiety", idankiety) :
                new ObjectParameter("idankiety", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WypelnijAnkiete_Result>("WypelnijAnkiete", idankietyParameter);
        }
    }
}
